repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args: ['--allow-multiple-documents']
  - id: check-added-large-files
- repo: https://github.com/nikhilgorantla/pre-commit
  rev: main
  hooks:
  - id: kustomize-build
  - id: kustomize-missing
- repo: https://github.com/jpachcuda/pre-commit-hooks
  rev: v0.1.2
  hooks:
  - id: delete-me
  - id: miss-kusto
