- id: delete-me
  name: Delete test kustomize
  description: This hook deletes files including deleteme in name
  entry: hooks/delete-me.sh
  language: script
  always_run: true
- id: miss-kusto
  name: Manifest missing from kustomization
  description: This hook checks for files missing from kustomization.yaml files
  entry: hooks/miss-kusto.sh
  language: script
  always_run: true
- id: software-docks
  name: Generate software docs from Dockerfile
  description: This hook generates a DOCS.md file with OS and Software based on Dockerfile
  entry: hooks/software-docks.sh
  language: script
  always_run: false